apiVersion: v1
kind: Service
metadata:
  name: "api-movies-service"
  namespace: "default"
  labels:
    app: "api-movies"
spec:
  ports:
  - port: 5000
    targetPort: http-server
  selector:
    app: api-movies
  type: LoadBalancer